# Generated by Django 5.0.6 on 2024-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('base', models.TextField()),
                ('viewers', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
