# Generated by Django 5.0.6 on 2024-06-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0002_alter_comentario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_comentarios/'),
        ),
    ]
