# Generated by Django 5.0.6 on 2024-05-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0002_comentario_delete_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='base',
            new_name='comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='viewers',
        ),
    ]
