# Generated by Django 5.0.6 on 2024-06-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0003_profile_autor_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
