# Generated by Django 5.0.6 on 2024-06-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='imagens_perfil/'),
        ),
    ]
