# Generated by Django 5.0.6 on 2024-06-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone_x_app', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
